### ISSUE TITLE
Spatial index throws exception when adding new element using spring-data-neo4j-rest v3.3.0

### ISSUE THREAD

**Issue by aabutaleb** [spring-projects/spring-data-neo4j#262]
Spatial is throwing an error when adding a new element to the index using the rest interface.
The following field: 

```java
@NodeEntity
public class Pub{
    @GraphId Long id;
    @Indexed(indexType = IndexType.POINT, indexName = "LocationIndex")
    private String wkt;
...
}
```

When adding a new element with wkt = "POINT(-12.130000 51.120000)"
I get this exception: 

```
{
"message": "NODE[30127] has no property with propertyKey=\"wkt\".",
"exception": "NotFoundException",
"fullname": "org.neo4j.graphdb.NotFoundException",
"stacktrace": [
    "org.neo4j.kernel.impl.core.NodeProxy.getProperty(NodeProxy.java:378)",
    "org.neo4j.gis.spatial.WKTGeometryEncoder.decodeGeometry(WKTGeometryEncoder.java:44)",
    "org.neo4j.gis.spatial.indexprovider.LayerNodeIndex.add(LayerNodeIndex.java:126)",
    "org.neo4j.gis.spatial.indexprovider.LayerNodeIndex.add(LayerNodeIndex.java:41)",
    "org.neo4j.server.rest.web.DatabaseActions.addToNodeIndex(DatabaseActions.java:708)",
    "org.neo4j.server.rest.web.RestfulGraphDatabase.addToNodeIndex(RestfulGraphDatabase.java:1058)",
    "java.lang.reflect.Method.invoke(Method.java:606)",
    "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)",
    "java.lang.Thread.run(Thread.java:745)"
],
"cause": {
    "message": "NODE[30127] has no property with propertyKeyId=20.",
    "exception": "PropertyNotFoundException",
    "fullname": "org.neo4j.kernel.api.exceptions.PropertyNotFoundException",
    "stacktrace": [
        "org.neo4j.kernel.api.properties.NoProperty.value(NoProperty.java:93)",
        "org.neo4j.kernel.impl.core.NodeProxy.getProperty(NodeProxy.java:374)",
        "org.neo4j.gis.spatial.WKTGeometryEncoder.decodeGeometry(WKTGeometryEncoder.java:44)",
        "org.neo4j.gis.spatial.indexprovider.LayerNodeIndex.add(LayerNodeIndex.java:126)",
        "org.neo4j.gis.spatial.indexprovider.LayerNodeIndex.add(LayerNodeIndex.java:41)",
        "org.neo4j.server.rest.web.DatabaseActions.addToNodeIndex(DatabaseActions.java:708)",
        "org.neo4j.server.rest.web.RestfulGraphDatabase.addToNodeIndex(RestfulGraphDatabase.java:1058)",
        "java.lang.reflect.Method.invoke(Method.java:606)",
        "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)",
        "java.lang.Thread.run(Thread.java:745)"
    ]
}
```
It looks like the properties are not saved into the DB when the new entry is being added to the index.

Tested and working fine with v3.2.2.RELEASE and previous. Not working from v3.3.0 onwards.
Using Spring 4.0.9.RELEASE and Neo4j 2.1.1 with Spatial 2.1.2

**Comment by jexp** [comment]
That's an issue of transaction isolation, the remote operations use now cypher which has transaction isolation on the endpoint but the manual indexes (spatial, full-text) are called via REST and don't participate in that transaction.

I started to work on this but didn't get it fixed in time for the GA release (was only reported jus before the weekend of the release).

Will have to find time to look into this.

**Comment by asompheng** [comment]
Hello @aabutaleb,

Since I got problem trying to make them (spatial, sdn-rest,neo4j) work together with last version (cf: http://stackoverflow.com/questions/30306498/compatibility-neo4j-spatial-with-spring-data-neo4j-rest-and-neo4j-ce-2-2-1-serve) I tried to build my app following your versions (spatial 0.13-neo4j-2.1.8, neo4j 2.1.8 and SDN 3.2.0.RELEASE) ... but I still get exception trying to create a layer :(

Below, my stack trace, do you have an idea why it does not work ?

```
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException
	at org.neo4j.cypher.ExecutionEngine.createCompiler(ExecutionEngine.scala:149)
	at org.neo4j.cypher.ExecutionEngine.<init>(ExecutionEngine.scala:48)
	at org.neo4j.cypher.javacompat.ExecutionEngine.createInnerEngine(ExecutionEngine.java:59)
	at org.neo4j.cypher.javacompat.ExecutionEngine.<init>(ExecutionEngine.java:43)
	at org.neo4j.gis.spatial.utilities.ReferenceNodes.getReferenceNode(ReferenceNodes.java:41)
	at org.neo4j.gis.spatial.SpatialDatabaseService.getSpatialRoot(SpatialDatabaseService.java:78)
	at org.neo4j.gis.spatial.SpatialDatabaseService.getLayer(SpatialDatabaseService.java:114)
	at org.neo4j.gis.spatial.SpatialDatabaseService.getOrCreateLayer(SpatialDatabaseService.java:208)
	at org.neo4j.gis.spatial.SpatialDatabaseService.getOrCreateLayer(SpatialDatabaseService.java:220)
```

**Comment by liebowitz** [comment]
I couldn't find any reasonable approach to resolve this in the 3.4.x release. The implementation is too tightly coupled with the legacy Lucene indexing operations.

It seems moving to the 4.x branch is the only practical solution to this issue. Then one can use an AfterSaveEvent to call the spatial REST API for adding the node to the layer - essentially "out of band".

**Comment by mangrish** [comment]
Closed. Issue out of date.
